<?php

declare(strict_types=1);

function articleMetadata(): array
{
  return [
    [
      'slug' => 'anmeldung-krok-po-kroku',
      'category' => 'urzedy',
      'title' => 'Anmeldung w Niemczech krok po kroku: jak zameldować się bez błędów',
      'description' => 'Praktyczny przewodnik po meldunku w Niemczech: dokumenty, terminy, opłaty i najczęstsze błędy nowych emigrantów.',
      'date' => '2026-01-15',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/anmeldung-krok-po-kroku.svg',
    ],
    [
      'slug' => 'steuer-id-jak-zdobyc',
      'category' => 'urzedy',
      'title' => 'Steuer-ID: jak zdobyć i do czego jest potrzebny numer podatkowy',
      'description' => 'Wyjaśniamy jak działa Steuer-ID, gdzie go znaleźć i kiedy urząd skarbowy wysyła numer podatkowy.',
      'date' => '2026-01-14',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/steuer-id-jak-zdobyc.svg',
    ],
    [
      'slug' => 'elster-rozliczenie-podatku',
      'category' => 'urzedy',
      'title' => 'ELSTER dla początkujących: rozliczenie podatku krok po kroku',
      'description' => 'Jak założyć konto ELSTER, wysłać deklarację i odzyskać nadpłatę podatku w Niemczech.',
      'date' => '2026-01-13',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/elster-rozliczenie-podatku.svg',
    ],
    [
      'slug' => 'kindergeld-wniosek',
      'category' => 'urzedy',
      'title' => 'Kindergeld 2026: jak wypełnić wniosek i nie stracić świadczenia',
      'description' => 'Checklista dokumentów i procedura składania wniosku o Kindergeld dla rodzin mieszkających w Niemczech.',
      'date' => '2026-01-12',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/kindergeld-wniosek.svg',
    ],
    [
      'slug' => 'karta-pobytu-dla-rodziny-ue',
      'category' => 'urzedy',
      'title' => 'Karta pobytu dla rodziny obywatela UE: procedura i terminy',
      'description' => 'Jak przygotować legalizację pobytu dla członków rodziny w Niemczech i uniknąć opóźnień.',
      'date' => '2026-01-11',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/karta-pobytu-dla-rodziny-ue.svg',
    ],
    [
      'slug' => 'ubezpieczenie-zdrowotne-wybor',
      'category' => 'urzedy',
      'title' => 'Ubezpieczenie zdrowotne w Niemczech: publiczne czy prywatne?',
      'description' => 'Porównanie GKV i PKV, koszty, składki oraz praktyczne wskazówki dla nowych emigrantów.',
      'date' => '2026-01-10',
      'tags' => ['formalności', 'urzędy', 'dokumenty'],
      'thumb' => '/assets/img/thumbs/ubezpieczenie-zdrowotne-wybor.svg',
    ],
    [
      'slug' => 'cv-po-niemiecku-profesjonalnie',
      'category' => 'praca',
      'title' => 'CV po niemiecku: wzór i zasady, które naprawdę działają',
      'description' => 'Jak napisać Lebenslauf pod niemiecki rynek pracy i zwiększyć liczbę zaproszeń na rozmowę.',
      'date' => '2026-01-09',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/cv-po-niemiecku-profesjonalnie.svg',
    ],
    [
      'slug' => 'list-motywacyjny-bewerbung',
      'category' => 'praca',
      'title' => 'Bewerbung w praktyce: list motywacyjny i komplet dokumentów',
      'description' => 'Sprawdzone standardy aplikacji o pracę w Niemczech: Anschreiben, Zeugnisse i portfolio.',
      'date' => '2026-01-08',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/list-motywacyjny-bewerbung.svg',
    ],
    [
      'slug' => 'rozmowa-kwalifikacyjna-niemcy',
      'category' => 'praca',
      'title' => 'Rozmowa kwalifikacyjna w Niemczech: pytania i dobre odpowiedzi',
      'description' => 'Jak przygotować się do rozmowy o pracę po niemiecku i pewnie negocjować warunki.',
      'date' => '2026-01-07',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/rozmowa-kwalifikacyjna-niemcy.svg',
    ],
    [
      'slug' => 'umowa-o-prace-niemcy',
      'category' => 'praca',
      'title' => 'Umowa o pracę w Niemczech: co sprawdzić przed podpisaniem',
      'description' => 'Kluczowe zapisy umowy, okres próbny, wypowiedzenie i ochrona pracownika.',
      'date' => '2026-01-06',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/umowa-o-prace-niemcy.svg',
    ],
    [
      'slug' => 'zmiana-pracy-bez-ryzyka',
      'category' => 'praca',
      'title' => 'Zmiana pracy w Niemczech bez ryzyka finansowego i prawnego',
      'description' => 'Plan przejścia do nowego pracodawcy z zachowaniem ciągłości dochodów i ubezpieczenia.',
      'date' => '2026-01-05',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/zmiana-pracy-bez-ryzyka.svg',
    ],
    [
      'slug' => 'samozatrudnienie-gewerbe',
      'category' => 'praca',
      'title' => 'Gewerbe i samozatrudnienie: jak legalnie zacząć działalność',
      'description' => 'Rejestracja Gewerbe, podatki i ubezpieczenia dla freelancerów i mikrofirm w Niemczech.',
      'date' => '2026-01-04',
      'tags' => ['kariera', 'praca', 'niemcy'],
      'thumb' => '/assets/img/thumbs/samozatrudnienie-gewerbe.svg',
    ],
    [
      'slug' => 'konto-bankowe-dla-emigranta',
      'category' => 'finanse',
      'title' => 'Konto bankowe w Niemczech: jak wybrać najlepsze dla emigranta',
      'description' => 'Porównanie opłat, kart, przelewów i wymagań banków dla nowych mieszkańców Niemiec.',
      'date' => '2026-01-03',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/konto-bankowe-dla-emigranta.svg',
    ],
    [
      'slug' => 'schufa-jak-dziala',
      'category' => 'finanse',
      'title' => 'SCHUFA: co to jest i jak poprawić swoją historię kredytową',
      'description' => 'Praktyczny poradnik budowania wiarygodności finansowej w Niemczech krok po kroku.',
      'date' => '2026-01-02',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/schufa-jak-dziala.svg',
    ],
    [
      'slug' => 'klasy-podatkowe-niemcy',
      'category' => 'finanse',
      'title' => 'Klasy podatkowe w Niemczech: jak wybrać właściwą i płacić mniej',
      'description' => 'Wyjaśniamy Steuerklassen i kiedy opłaca się zmiana klasy podatkowej.',
      'date' => '2026-01-01',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/klasy-podatkowe-niemcy.svg',
    ],
    [
      'slug' => 'budzet-domowy-w-euro',
      'category' => 'finanse',
      'title' => 'Budżet domowy emigranta: jak kontrolować wydatki w euro',
      'description' => 'System planowania finansów dla rodzin i singli mieszkających w Niemczech.',
      'date' => '2025-12-31',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/budzet-domowy-w-euro.svg',
    ],
    [
      'slug' => 'kredyt-samochodowy-niemcy',
      'category' => 'finanse',
      'title' => 'Kredyt samochodowy w Niemczech: warunki i pułapki umów',
      'description' => 'Na co zwrócić uwagę przy finansowaniu auta i jak obniżyć koszt całkowity kredytu.',
      'date' => '2025-12-30',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/kredyt-samochodowy-niemcy.svg',
    ],
    [
      'slug' => 'emerytura-w-niemczech-dla-polakow',
      'category' => 'finanse',
      'title' => 'Emerytura w Niemczech dla Polaków: składki, staż i wypłata',
      'description' => 'Jak liczy się emerytura, jakie dokumenty gromadzić i jak połączyć okresy pracy.',
      'date' => '2025-12-29',
      'tags' => ['finanse', 'budżet', 'podatki'],
      'thumb' => '/assets/img/thumbs/emerytura-w-niemczech-dla-polakow.svg',
    ],
    [
      'slug' => 'jak-znalezc-mieszkanie-berlin',
      'category' => 'mieszkanie',
      'title' => 'Jak znaleźć mieszkanie w Niemczech: skuteczna strategia od A do Z',
      'description' => 'Proces najmu, dokumenty i negocjacje z wynajmującym na konkurencyjnym rynku.',
      'date' => '2025-12-28',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/jak-znalezc-mieszkanie-berlin.svg',
    ],
    [
      'slug' => 'umowa-najmu-co-sprawdzic',
      'category' => 'mieszkanie',
      'title' => 'Umowa najmu w Niemczech: co sprawdzić zanim podpiszesz Mietvertrag',
      'description' => 'Najważniejsze klauzule, koszty dodatkowe i prawa lokatora.',
      'date' => '2025-12-27',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/umowa-najmu-co-sprawdzic.svg',
    ],
    [
      'slug' => 'kaucja-i-nebenkosten',
      'category' => 'mieszkanie',
      'title' => 'Kaucja i Nebenkosten: jak nie przepłacić za mieszkanie',
      'description' => 'Jak działa kaucja, rozliczenia kosztów dodatkowych i procedura zwrotu depozytu.',
      'date' => '2025-12-26',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/kaucja-i-nebenkosten.svg',
    ],
    [
      'slug' => 'meldunek-po-przeprowadzce',
      'category' => 'mieszkanie',
      'title' => 'Meldunek po przeprowadzce: obowiązki lokatora w Niemczech',
      'description' => 'Terminy i formalności po zmianie adresu, aby uniknąć kar administracyjnych.',
      'date' => '2025-12-25',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/meldunek-po-przeprowadzce.svg',
    ],
    [
      'slug' => 'media-i-internet-po-umowie',
      'category' => 'mieszkanie',
      'title' => 'Media i internet po podpisaniu umowy najmu: praktyczny setup',
      'description' => 'Elektryczność, gaz, internet i ubezpieczenia mieszkania krok po kroku.',
      'date' => '2025-12-24',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/media-i-internet-po-umowie.svg',
    ],
    [
      'slug' => 'wypowiedzenie-najmu-niemcy',
      'category' => 'mieszkanie',
      'title' => 'Wypowiedzenie najmu w Niemczech: terminy, wzór i odbiór lokalu',
      'description' => 'Jak bezpiecznie zakończyć najem i odzyskać kaucję bez konfliktu.',
      'date' => '2025-12-23',
      'tags' => ['najem', 'mieszkanie', 'lokator'],
      'thumb' => '/assets/img/thumbs/wypowiedzenie-najmu-niemcy.svg',
    ],
    [
      'slug' => 'koszty-zycia-niemcy-2026',
      'category' => 'zycie',
      'title' => 'Koszty życia w Niemczech 2026: realne wydatki i plan minimum',
      'description' => 'Ile kosztuje życie w Niemczech i jak ustawić budżet już od pierwszego miesiąca.',
      'date' => '2025-12-22',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/koszty-zycia-niemcy-2026.svg',
    ],
    [
      'slug' => 'opieka-zdrowotna-na-co-dzien',
      'category' => 'zycie',
      'title' => 'Opieka zdrowotna na co dzień: lekarz rodzinny, specjaliści i recepty',
      'description' => 'Jak korzystać z niemieckiej służby zdrowia bez stresu i zbędnych kosztów.',
      'date' => '2025-12-21',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/opieka-zdrowotna-na-co-dzien.svg',
    ],
    [
      'slug' => 'szkola-i-przedszkole-dla-dzieci',
      'category' => 'zycie',
      'title' => 'Szkoła i przedszkole w Niemczech: praktyczny przewodnik dla rodziców',
      'description' => 'Zapisy, dokumenty i wsparcie językowe dla dzieci polskich rodzin.',
      'date' => '2025-12-20',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/szkola-i-przedszkole-dla-dzieci.svg',
    ],
    [
      'slug' => 'integracja-i-jezyk-w-praktyce',
      'category' => 'zycie',
      'title' => 'Integracja i język: jak szybciej odnaleźć się w niemieckiej codzienności',
      'description' => 'Skuteczne metody nauki języka i budowania relacji lokalnie.',
      'date' => '2025-12-19',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/integracja-i-jezyk-w-praktyce.svg',
    ],
    [
      'slug' => 'transport-publiczny-i-auto',
      'category' => 'zycie',
      'title' => 'Transport publiczny i samochód w Niemczech: co się bardziej opłaca',
      'description' => 'Koszty biletów, paliwa i ubezpieczenia auta dla mieszkańców dużych i małych miast.',
      'date' => '2025-12-18',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/transport-publiczny-i-auto.svg',
    ],
    [
      'slug' => 'bezpieczenstwo-i-prawo-konsumenta',
      'category' => 'zycie',
      'title' => 'Bezpieczeństwo i prawa konsumenta w Niemczech: praktyka na co dzień',
      'description' => 'Jak reagować na oszustwa, reklamacje i nieuczciwe umowy.',
      'date' => '2025-12-17',
      'tags' => ['życie codzienne', 'integracja', 'poradnik'],
      'thumb' => '/assets/img/thumbs/bezpieczenstwo-i-prawo-konsumenta.svg',
    ],
  ];
}
